version: "3"

services:

  # ----------------------------------------------------------------------------

  database:
    image: mysql:8
    working_dir: /var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
      - ./logs/mysql:/opt/logs/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=laravel_local
      - MYSQL_ROOT_PASSWORD=secret
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=secret
    ports:
      - 33060:3306

  # ----------------------------------------------------------------------------

  php:
    build: ./infra/php/
    working_dir: /work
    volumes:
      - ./backend:/work
      - ./logs/php-fpm:/opt/logs/php-fpm
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini:ro
    links:
      - database:db
    ports:
      - 9000:9000

  # ----------------------------------------------------------------------------

  nginx:
    image: nginx:1.20
    working_dir: /work
    volumes:
      - ./backend:/work
      - ./logs/nginx:/opt/logs/nginx
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    links:
      # infra/nginx/default.conf: fastcgi_pass app:9000;
      - php:app
    ports:
      - 10080:80

  # ----------------------------------------------------------------------------
